### ISSUE TITLE
댓글 달기와 관련된 세 가지 이슈 입니다.

### ISSUE THREAD

**Issue by ericKwon95** [BeHealthy3/PoorGuys#16]
* 게시글 에서 댓글쓰기를 클릭했을 때 프로필 사진이 마이페이지의 프로필 사진이 아닌 랜덤 사진이 뜹니다.
* 아무 내용도 없는 빈 댓글을 달 수 있습니다.
* 댓글 쓰기를 취소할 수 있는 액션을 추가해야 할 것 같습니다. 현재는 댓글을 달지 않고 취소할 수 있는 액션이 없어 보입니다.

**Comment by ThisIsEHD** [comment]
우선 댓글 쓰기 취소 기능은 일단 일부러 만들지 않았습니다. 디자인, 기획적으로 어떻게 풀어나가야 할지 감이 안오더라구요. 그래서 레퍼런스를 참고하니 저희와 같은 디자인을 통해 커뮤니티를 풀어내는 앱들은 해당 기능이 없었습니다. (에타는 댓을 쓰다가 다른 곳을 터치하면 댓글작성 취소 여부에 대한 알림창이 뜨고 거기서 댓글작성취소를 선택하면 댓글이 전부 지워지는 방식이었는데 그 방법은 개인적으로 유저입장에서 불편하다고 생각했습니다.) 아무래도 댓글달기를 취소하고나서 할만한 작업이 해당 뷰에서 없기 때문이지 않을까 싶습니다. 댓을 달다가 다른 작업을 다 할 수 있고 그게 딱히 어색하지 않으니까요. 물론 확인버튼만 안누르면 댓글이 달리지 않기 때문에 취소가 반드시 필요하지 않은 것도 있구요. 혹시라도 해당 기능이 아주 필요하다고 생각하시면 회의에서 안건 제안해주시면 좋을 것 같습니다.

**Comment by ericKwon95** [comment]
@ThisIsEHD 자세한 설명 감사합니다. 댓글 작성을 완전히 취소하는 기능은 없어도 될 것 같다는 점에 동의합니다. 다만 현재 댓글 작성 중 키보드가 올라와 있을 때 다른 영역을 터치해도 키보드가 내려가지 않고 댓글 작성 완료를 눌러야만 키보드를 사라지게 할 수 있습니다. 이 부분은 키보드와 텍스트필드를 제외한 영역을 터치하면 키보드가 내려가도록 구현하면 좋을 것 같은데, 에드님 생각은 어떠신가요?

**Comment by ThisIsEHD** [comment]
아 해당부분 제가 fix 브랜치에서 구현했는데 푸시를 안했던 것 같습니다. 차후에 제가 올리겠습니다~

**Comment by ericKwon95** [comment]
아하 그러셨군요 그러면 이 이슈는 닫도록 하겠습니다~!
