### ISSUE TITLE
로그인 관련 이슈

### ISSUE THREAD

**Issue by ThisIsEHD** [BeHealthy3/PoorGuys#18]
@ericKwon95 
지금 제가 메인브랜치에서 회원가입이 안되어있는 계정으로 구글 "회원가입"을 시도하니까 아래와 같은 콘솔은 뜨는데 화면이 닉네임 설정창으로 전환되지 않습니다. users collection에 다큐먼트는 생성되는데 nickname은 설정하지 않아서 ""로 설정됩니다. 그래서 제가 강제로 document찾아가서 nickname에 "개발자" 라고 닉네임을 부여한 후에 다시 시도 해봐도 여전히 뷰가 전환되지 않습니다. 확인 부탁드릴게요!

*참고 "isUserDataStoredInFirestore" 함수 내의 "// user의 id를 이름으로하는 Collection 참조" 주석 아래의 코드는 제가 실수로 만들었는데 삭제하지 않은 부분입니다. 이번 커밋에서 삭제할 예정이니까 무시해서 봐주세요!

------
유저 auth 로그인 완료 / uid : WqKrXfZUWkhN8yoIymbkR1X1cOm1
해당하는 유저 없음
새로운 유저 firestore에 등록 완료
------

**Comment by ThisIsEHD** [comment]
*업데이트: 참고부분의 코드는 제가 삭제한후 메인에 머지하였습니다. 메인 풀 한번 해주시면 되겠습니다.

**Comment by ThisIsEHD** [comment]
8월 10일 "e0c8baad67345a65399a2399bb25da0da0e9bf87" 커밋에서는 회원가입 시도하면 setNicknameView 가 뜨는 것으로 확인됩니다. 반면 또 거기서는 "메인페이지로" 버튼을 눌렀을 때 메인으로 가지 않네요... 해당 부분 고려하셔서 총체적으로 이부분 확인 해주시면 좋을 것 같습니다!

**Comment by ericKwon95** [comment]
상세한 확인 감사합니다! #20 에 관련 문제 수정해 PR하였습니다.
